version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5433:5432
    networks:
      - postgres_network
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=17009839
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tractor_plant

  pgadmin:
    depends_on:
      - "postgres"
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - postgres_network

  backend:
    container_name: backend
    build:
      context: ./db_cp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - postgres_network
      - nginx_network
    depends_on:
      - postgres

  vue:
    container_name: front
    build:
      context: ./web-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./web-front:/usr/src/app
    environment:
      NODE_ENV: development

  nginx:
    image: "byjg/nginx-extras"
    container_name: nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/static:/static
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - nginx_network


networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge

